
  import { defineConfig } from 'vite';
  import react from '@vitejs/plugin-react-swc';
  import path from 'path';

  export default defineConfig({
    plugins: [react()],
    resolve: {
      extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
      alias: {
        'vaul': 'vaul',
        'sonner': 'sonner',
        'recharts': 'recharts',
        'react-resizable-panels': 'react-resizable-panels',
        'react-hook-form': 'react-hook-form',
        'react-day-picker': 'react-day-picker',
        'next-themes': 'next-themes',
        'lucide-react': 'lucide-react',
        'input-otp': 'input-otp',
        'figma:asset/84b46758cf032fd795cecf60b64632dede907894.png': path.resolve(__dirname, './src/assets/84b46758cf032fd795cecf60b64632dede907894.png'),
        'figma:asset/4c5b75d1d1f44b879cc0ffb4b315ece4b0ebb532.png': path.resolve(__dirname, './src/assets/4c5b75d1d1f44b879cc0ffb4b315ece4b0ebb532.png'),
        'figma:asset/31388e4677c0ee7ab2855a26d80d60468ad46b6b.png': path.resolve(__dirname, './src/assets/31388e4677c0ee7ab2855a26d80d60468ad46b6b.png'),
        'embla-carousel-react': 'embla-carousel-react',
        'cmdk': 'cmdk',
        'class-variance-authority': 'class-variance-authority',
        '@radix-ui/react-tooltip': '@radix-ui/react-tooltip',
        '@radix-ui/react-toggle': '@radix-ui/react-toggle',
        '@radix-ui/react-toggle-group': '@radix-ui/react-toggle-group',
        '@radix-ui/react-tabs': '@radix-ui/react-tabs',
        '@radix-ui/react-switch': '@radix-ui/react-switch',
        '@radix-ui/react-slot': '@radix-ui/react-slot',
        '@radix-ui/react-slider': '@radix-ui/react-slider',
        '@radix-ui/react-separator': '@radix-ui/react-separator',
        '@radix-ui/react-select': '@radix-ui/react-select',
        '@radix-ui/react-scroll-area': '@radix-ui/react-scroll-area',
        '@radix-ui/react-radio-group': '@radix-ui/react-radio-group',
        '@radix-ui/react-progress': '@radix-ui/react-progress',
        '@radix-ui/react-popover': '@radix-ui/react-popover',
        '@radix-ui/react-navigation-menu': '@radix-ui/react-navigation-menu',
        '@radix-ui/react-menubar': '@radix-ui/react-menubar',
        '@radix-ui/react-label': '@radix-ui/react-label',
        '@radix-ui/react-hover-card': '@radix-ui/react-hover-card',
        '@radix-ui/react-dropdown-menu': '@radix-ui/react-dropdown-menu',
        '@radix-ui/react-dialog': '@radix-ui/react-dialog',
        '@radix-ui/react-context-menu': '@radix-ui/react-context-menu',
        '@radix-ui/react-collapsible': '@radix-ui/react-collapsible',
        '@radix-ui/react-checkbox': '@radix-ui/react-checkbox',
        '@radix-ui/react-avatar': '@radix-ui/react-avatar',
        '@radix-ui/react-aspect-ratio': '@radix-ui/react-aspect-ratio',
        '@radix-ui/react-alert-dialog': '@radix-ui/react-alert-dialog',
        '@radix-ui/react-accordion': '@radix-ui/react-accordion',
        '@': path.resolve(__dirname, './src'),
      },
    },
    build: {
      target: 'esnext',
      outDir: 'build',
    },
    server: {
      port: 3000,
      open: true,
    },
  });